services:
#  database:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: portfolio_db
#    ports:
#      - "5432:5432"
#    networks:
#      - backend
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - backend
#
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - backend

  discovery-service:
    build: ./backend/DiscoveryServer
    ports:
      - "8761:8761"
    networks:
      - backend

#  notification-service:
#    build: ./backend/notification-service
#    depends_on:
#      - kafka
#    ports:
#      - "8083:8083"
#    networks:
#      - backend

  reporting-service:
    build: ./backend/reporting-service
    depends_on:
#      - kafka
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8008:8008"
    networks:
      - backend

networks:
  backend:
    driver: bridge
#  frontend:
#    driver: bridge
